### ISSUE TITLE
IAR __packed needs to be before struct and union keywords

### ISSUE THREAD

**Issue by LACoopConsulting** [IntergatedCircuits/USBDevice#14]
usbd_desc.c, usbd_desc,h usb_types.h, and the source/header files for device classes (e.g. usbd_cdc.c and usbd_cdc.h) specify typedefs and declare instances of packed structs and unions as follows:

`typedef struct { ... } __packed TYPE_NAME`
`struct { ... } __packed INSTANCE_NAME `
and so forth. 

Based on empirical testing with the console_if.c class, USBDevice, and USBDevice4Cube, it appears IAR does not handle this syntax as expected. In particular, the configuration descriptor bytes that are sent during enumeration are malformed, causing the host to retry a few times and then reject the device. 

This [document](https://www.iar.com/contentassets/e20cfa542d1a4734aa6b234bea42f11a/example-5.pdf) from IAR gives the impression that `__packed struct` and `__packed union` would be the appropriate syntax. This is further given credence by the defines in `cmsis_iccarm.h` of `#define __PACKED_STRUCT __packed struct` and `#define __PACKED UNION __packed union` 

Moving `__packed` in front of `struct` and `union` in the files mentioned above appeared to fix the issue for IAR and the `console_if.c` example. No testing was done on what impact, if any, this has on other compilers/toolchains, as such this is only an issue listing and not a pull request.

**Comment by IntergatedCircuits** [comment]
I have added a fix to address this issue, without breaking support for GCC.
