### ISSUE TITLE
Fix build warning (error) in usbd_msc_scsi.c

### ISSUE THREAD

**Issue by lukebayes** [IntergatedCircuits/USBDevice#22]
```bash
C/usbd_msc_scsi.d" -MT"Dist/obj/USBDevice/Class/MSC/usbd_msc_scsi.o" --specs=nano.specs -mthumb -o "Dist/obj/USBDevice/Class/MSC/usbd_msc_scsi.o"                          
Vendor/USBDevice/Class/MSC/usbd_msc_scsi.c:62:35: error: excess elements in array initializer [-Werror]
   62 |     .SupportedPages     = { 0x00, 0x80 },                                    
      |                                   ^~~~                                 
compilation terminated due to -Wfatal-errors. 
```

[Line 62 of usbd_msc_scsi.c](https://github.com/IntergatedCircuits/USBDevice/blob/master/Class/MSC/usbd_msc_scsi.c#L62) initializes the collection with 2 entries, but the [declaration on line 42](https://github.com/IntergatedCircuits/USBDevice/blob/master/Class/MSC/usbd_msc_scsi.c#L42) only supports a single entry.

Please either truncate the number of initialized values, or increase the available entries in the declaration.

**Comment by IntergatedCircuits** [comment]
The commit is removed from master.

**Comment by lukebayes** [comment]
Thanks!
