### ISSUE TITLE
HID InData callback

### ISSUE THREAD

**Issue by alitekin2fx** [IntergatedCircuits/USBDevice#27]
Is there any particular reason why the HID doesn't have an InData callback?

**Comment by benedekkupper** [comment]
It's not added because it hasn't been a use-case so far, the HID applications I've worked on triggered the IN data transmission on external events. Does your application require the use of it?

**Comment by alitekin2fx** [comment]
Yes, I try to use your library in my CMSIS DAP project. It needs IN and OUT endpoints.

**Comment by benedekkupper** [comment]
OK, I'm adding this request to my work queue, ETC 1 week. If it's more urgent, you can do it yourself as well, just add an `InData` function to `hid_cbks` and redirect it to the application callback.

**Comment by alitekin2fx** [comment]
Thank you.

**Comment by benedekkupper** [comment]
Hi Ali, please try this master now, and close the ticket if it satisfies your requirements.
