### ISSUE TITLE
HID output endpoint is opened with wrong maximum packet size

### ISSUE THREAD

**Issue by FelixGruetzmacher** [IntergatedCircuits/USBDevice#31]
Looking at usbd_hid.c, line 295:
mps = HID_APP(itf)->Report->Input.MaxSize;
With very high confidence this should be Output.MaxSize as it is used for opening the output endpoint.
Our device is one of those special cases with long output reports and relatively small input reports, so we were bound to discover this one. :)

**Comment by benedekkupper** [comment]
Thanks for catching this bug and finding the root cause, the fix is pushed.
