### ISSUE TITLE
ncm:Out in itf

### ISSUE THREAD

**Issue by momoxuelin** [IntergatedCircuits/USBDevice#33]
Hi,I'm a newbie，I want to use ncm in my project, but I don't know why there are two Out page in itf?

**Comment by momoxuelin** [comment]
Or is there any documentation to help me understand the source code?

**Comment by benedekkupper** [comment]
The comment says "Received NTB status and double buffer" which is really all you need to know. You should look at the USBD_NCM_Exported_Functions section of functions, which is the public API of the class. For a demonstration project on how NCM can be integrated and used, see [IPoverUSB](https://github.com/IntergatedCircuits/IPoverUSB) project. If you want to understand the internal operation of the source code, you can read the comments in the file, and read the USB NCM class specification.

**Comment by momoxuelin** [comment]
OK, thank you very much.
