### ISSUE TITLE
SetReport callback data is shifted

### ISSUE THREAD

**Issue by zzattack** [IntergatedCircuits/USBDevice#4]
I'm noticing in the SetReport callback, when using Report ID's, the data in dev->CtrlData appears to be shifted by 1 place.

Using report ID `0x44` and sending payload `0x55 0xAA  0x55 0xAA  0x55 0xAA  0x55 0xAA`, it shows the following contents for `dev->CtrlData` in `hid_dataStage`

```
dev->CtrlData |  uint8_t [256]
  | [0] | 0x22 '"' | uint8_t
  | [1] | 0x44 'D' | uint8_t
  | [2] | 0x55 'U' | uint8_t
  | [3] | 0xaa 'ª' | uint8_t
  | [4] | 0x55 'U' | uint8_t
  | [5] | 0xaa 'ª' | uint8_t
  | [6] | 0x55 'U' | uint8_t
  | [7] | 0xaa 'ª' | uint8_t
  | [8] | 0x55 'U' | uint8_t
  | [9] | 0xaa 'ª' | uint8_t
```

`CtrlData[0]` seems to contain some data perhaps related to setup value?

When not using report id's, the data starts at CtrlData[0].

**Comment by IntergatedCircuits** [comment]
The idea is that the report data layout is the same, regardless of whether it is received through the control pipe or the interrupt pipe. So for control transfers the report ID - which is extracted from the Setup's Value field - is inserted in front of the regular data. Can you check what is the content of the Setup request's Value field in this case?

**Comment by zzattack** [comment]
I am unable to reproduce it for a few days but the 0x22 certainly was not the MSB of SetupValue. Will add that info when I can.

**Comment by IntergatedCircuits** [comment]
I made some corrections on the HID code, which affects this issue (mostly ensuring proper alignment for control transfers with report IDs), I hope this doesn't occur with the new version.

**Comment by zzattack** [comment]
Had some trouble reproducing this but succeeded eventually. Unsure of the circumstances but after updating the USB lib the alignment indeed was corrected indeed.

**Comment by IntergatedCircuits** [comment]
In the setup stage the actual control data is received to `&CtrlData[4]`. The data stage places the report ID to `CtrlData[3]`, and passes `&CtrlData[3]` to the application callback. On my side it produces correct behavior: the report ID is always in the first byte of the report, regardless of whether it was a control transfer (Get/Set Report) or an interrupt one.

I use the [Microsoft Message Analyzer](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/capture-and-view-ing-usb-traces-with-microsoft-message-analyzer-) to check the actual USB transfers and verify the functionality. I recommend that you record the problematic transfers with a similar tool, in order to find the root cause of the issue.

**Comment by zzattack** [comment]
Hopefully this [screenshot](https://files.zzattack.org/img/upload/devenv_2018-07-11_22-18-48.png) sheds some light.
I verified that my report id is directly followed by the payload.
The breakpoint in hid_datastage hits immediately and the contents of `dev->CtrlData` showing the payload starts at `dev->CtrlData[5]` are visible.

**Comment by IntergatedCircuits** [comment]
I see what I expected to see. If you do catch it behaving differently send context data or screenshot.

**Comment by zzattack** [comment]
After the `data += 3` and setting `data[0] = report id`,  *data would start with `44 44 00 00 4C`. The report id is in there twice.

**Comment by IntergatedCircuits** [comment]
The data stage of the control request transfers 9 bytes: {44 00 00 3C 00 00 00 00 00}. The report ID should only be encoded in the wValue of the setup stage, and the data stage should only contain the report data. In this case it seems that the host sends the report ID in the data stage as well, which deviates from standard HID operation.

**Comment by zzattack** [comment]
This is the result of a `HidD_SetFeature` call. MS specifically requires the report id to be the first byte of the buffer, but it is not specified whether or not this value ends up in both the setup value as well as the payload. Seems odd to me that MS would not adhere to standard HID operations but I suppose knowing that it doesn't suffices.

**Comment by IntergatedCircuits** [comment]
I double checked the specification, and it seems like I was wrong the whole time. I apologize for the trouble. The report ID in the setup stage is really only necessary during the GetReport to identify which report is requested. The report ID is always the first byte of a record data when IDs are used. I pushed changes that not only correct this but add a report type parameter to the callbacks as well. It's necessary to update the application side accordingly.

**Comment by zzattack** [comment]
Now everything turns up as expected, thanks!
Also thanks for implementing the suggestion in https://github.com/IntergatedCircuits/USBDevice/issues/2 as well.
