### ISSUE TITLE
Wrong reference assigned to altSel

### ISSUE THREAD

**Issue by Coconop** [IntergatedCircuits/USBDevice#7]
In _usbd_if.c_ l.126 there is an extra `&`: we try to assign an `uint16_t*` to an `uint8_t`
`uint8_t altSel = (uint8_t)&dev->Setup.Value;`
IMHO it should be:
`uint8_t altSel = (uint8_t)(0xFF & dev->Setup.Value);`

**Comment by IntergatedCircuits** [comment]
Thanks for the findings, keep up the good work!
